name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.5.0

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'

      - name: Add auth
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.CI_READ_PACKAGE_TOKEN }}" >> .npmrc

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm build:prod
